#!/bin/sh
echo "EVALUATING USER"
git clone $1 userproject -q
clear
./spawn.pl userproject "config_d$2.pl"
clear
./tools/build.sh
clear

echo "+-+-+-+-+-+-+-+-+-+-+" >> RESULT.txt
echo "|N|o|r|m|i|n|e|t|t|e|" >> RESULT.txt
echo "+-+-+-+-+-+-+-+-+-+-+\n" >> RESULT.txt

./tools/verify.sh >> RESULT.txt

echo "\n+-+-+-+-+-+-+-+-+-+-+" >> RESULT.txt
echo "|M|o|u|l|i|n|e|t|t|e|" >> RESULT.txt
echo "+-+-+-+-+-+-+-+-+-+-+\n" >> RESULT.txt

./tools/check_all.sh >> RESULT.txt

cp RESULT.txt ~/Desktop
